spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:common/db/migration,classpath:stag/db/migration

logging:
  level:
    com.smartvizz.expenses.backend: DEBUG
