app:
  baseUrl: ${APP_BASE_URL:''}  # Dynamic base URL, with empty string as default

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}  # Active profile, sourced from the environment

  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}  # MySQL username from the environment
    password: ${SPRING_DATASOURCE_PASSWORD}  # MySQL password from the environment
    url: ${SPRING_DATASOURCE_URL}  # MySQL URL from the environment

  jpa:
    hibernate:
      ddl-auto: validate  # Hibernate DDL auto setting

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:common/db/migration

  mail:
    host: ${MAIL_HOST}  # Mail server host from environment
    port: ${MAIL_PORT}  # Mail server port from environment
    username: ${MAIL_USERNAME}  # Mail server username from environment
    password: ${MAIL_PASSWORD}  # Mail server password from environment
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH}  # SMTP auth from environment
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE}  # SMTP STARTTLS enable from environment

jwt:
  secret: ${JWT_SECRET}  # JWT secret key from environment
  expiration: ${JWT_EXPIRATION:3600000}  # JWT expiration time in milliseconds from environment, defaulting to 1 hour
