app:
  baseUrl: http://localhost:8880
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:common/db/migration,classpath:dev/db/migration

logging:
  level:
    com.smartvizz.expenses.backend: DEBUG
jwt:
  secret: E21h/sJwq9sQ9OqhfgKTRU1S9uJc6g1kKis+S8fP8fA=
  expiration: 3600000  #1 hour in milliseconds
